services:
  accounts:
    image: "dhiraj82/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
         - learnms
  loans:
    image: "dhiraj82/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - learnms
  cards:
    image: "dhiraj82/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - learnms
networks:
  learnms:
    driver: "bridge"