
server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to Dummy Bank Cards related local APIs "
  contactDetails:
    name: "Vipul Tyagi - Developer"
    email: "vipul@dummybank.com"
  onCallSupport:
    - (555) 555-4321
    - (555) 523-5678