spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Dhiraj050882/MSConfigurations.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "File:///D://Learning_Projects//Microservices//Section_6//V2-spring-cloud-config//configserver//src//main//resources//config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "W6iIqtRJRWCChkOuCs1gp"


server:
  port: 8071
