spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-location: "File:///D://Learning_Projects//Microservices//Section_6//V2-spring-cloud-config//configserver//src//main//resources//config"

server:
  port: 8071

